HRJS-36 SASL Authentication
infinispan/js-client pull request #54
Opened 2021-06-15 08:26 UTC by tristantarrant

https://issues.redhat.com/browse/HRJS-36

2021-06-16 15:09 UTC, karesti requested changes
I commented stuff to run faster some stuff and tests but need to be rollbacked. otherwise LGTM!

2021-06-16 15:09 UTC, karesti commented on run-testsuite.sh
> -node --trace-deprecation node_modules/jasmine-node/lib/jasmine-node/cli.js spec/* --captureExceptions
needs to be rollbacked (modified for quick run only)

2021-06-16 15:09 UTC, karesti commented on run-servers.sh
> +#startServer "$1" infinispan-clustered.xml false 11322 "server-one"
needs to be rollbacked to run all the tests

2021-06-16 15:10 UTC, karesti commented
@tristantarrant needs rebase for the run-servers. I can do it

2021-06-16 15:19 UTC, karesti approved these changes

2021-06-16 15:50 UTC, tristantarrant commented
I've added docs to the README and the jsdoc

2021-06-17 13:10 UTC, karesti approved these changes

2021-06-17 13:10 UTC, merged